spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/lavanda?authSource=admin
  rabbitmq:
    username: user
    password: bitnami
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 1
          max-interval: 10s
          multiplier: 2
